In [19]:
%reload_ext autoreload
%autoreload 2

from functions import *
import pandas as pd
from pandas.api.types import CategoricalDtype
import time

pd.set_option('display.float_format', '{:.2f}'.format)
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 200)

In [20]:
# tier_decks = ["Angry Hermit", "Aluren", "Burn", "BW Control", "Deadguy Ale",
#          "Devourer Combo", "Elves", "Enchantress", "Goblins", "Gro-A-Tog",
#          "Landstill", "Madness", "Mono Black", "MUD", "Oath", "Parallax Replenish",
#          "Ponza", "Psychatog", "Stasis", "Stiflenought", "Terrageddon", "The Rock",
#          "White Weenie"]

In [21]:
deck = "Ponza"
format = "Premodern"
n_pages = 5

In [22]:
# download_decklists(deck, format, n_pages)

In [23]:
df = read_decklists(deck, format)
df = process_decklists(df, format)
df.type.unique()

array(['Acceleration', 'Artifact', 'Artifact Creature', 'Creature',
       'Enchantment', 'Finisher', 'Instant', 'Land', 'Other', 'Removal',
       'Sorcery', 'Tutor', nan, 'Hate'], dtype=object)

In [24]:
cards = analyze_dls_cards(df, types=True)
types = analyze_dls_types(df, subtypes=False)

In [25]:
for i, deck_colors in enumerate(df.deck_colors.unique()):
    n_decks_colors = df[df.deck_colors == deck_colors]["#dl"].nunique()
    total_decks = df["#dl"].nunique()
    print(f"Index {i} - {deck_colors}: {n_decks_colors} / {total_decks} decks ({n_decks_colors/total_decks:.2%})")

Index 0 - BR: 3 / 115 decks (2.61%)
Index 1 - BRG: 2 / 115 decks (1.74%)
Index 2 - G: 26 / 115 decks (22.61%)
Index 3 - R: 56 / 115 decks (48.70%)
Index 4 - RG: 23 / 115 decks (20.00%)
Index 5 - UR: 1 / 115 decks (0.87%)
Index 6 - WB: 2 / 115 decks (1.74%)
Index 7 - WR: 1 / 115 decks (0.87%)
Index 8 - WRG: 1 / 115 decks (0.87%)

In [32]:
cards[2]

,deck_colors,sb,final_qty,name,type,subtype,n_dls,sum,mean_rnd,mean,std,%_dls_w_card,mode_1st,%_mode_1st,mode_2nd,%_mode_2nd,mode_3rd,%_mode_3rd,mode_4th,%_mode_4th,mode_5th,%_mode_5th,min,max,% copies = mean-2,% copies = mean-1,% copies = mean,% copies = mean+1,% copies = mean+2,diff
0,G,0,0.00,Mox Diamond,Acceleration,Tier 1,26,8,0,0.31,1.09,0.08,0,0.92,4.00,0.08,NaN,0.00,NaN,0.00,NaN,0.00,0,4,0.00,0.00,0.92,0.00,0.00,-0.31
1,G,0,1.00,Tangle Wire,Artifact,unknown,26,33,1,1.27,1.82,0.35,0,0.65,4.00,0.27,2.00,0.04,3.00,0.04,NaN,0.00,0,4,0.00,0.65,0.00,0.04,0.04,-0.27
2,G,0,1.00,Smokestack,Artifact,unknown,26,20,1,0.77,1.48,0.23,0,0.77,4.00,0.12,3.00,0.08,2.00,0.04,NaN,0.00,0,4,0.00,0.77,0.00,0.04,0.08,0.23
3,G,0,1.00,Cursed Scroll,Artifact,unknown,26,19,1,0.73,1.08,0.35,0,0.65,2.00,0.23,3.00,0.08,1.00,0.04,NaN,0.00,0,3,0.00,0.65,0.04,0.23,0.08,0.27
4,G,0,1.00,Icy Manipulator,Artifact,unknown,26,18,1,0.69,0.93,0.38,0,0.62,2.00,0.31,1.00,0.08,NaN,0.00,NaN,0.00,0,2,0.00,0.62,0.08,0.31,0.00,0.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,G,1,0.00,Pyroclasm,Sorcery,unknown,26,0,0,0.00,0.00,0.00,0,1.00,NaN,0.00,NaN,0.00,NaN,0.00,NaN,0.00,0,0,0.00,0.00,1.00,0.00,0.00,0.00
320,G,1,0.00,Raze,Sorcery,unknown,26,0,0,0.00,0.00,0.00,0,1.00,NaN,0.00,NaN,0.00,NaN,0.00,NaN,0.00,0,0,0.00,0.00,1.00,0.00,0.00,0.00
321,G,1,0.00,Simplify,Sorcery,unknown,26,0,0,0.00,0.00,0.00,0,1.00,NaN,0.00,NaN,0.00,NaN,0.00,NaN,0.00,0,0,0.00,0.00,1.00,0.00,0.00,0.00
322,G,1,0.00,Slice and Dice,Sorcery,unknown,26,0,0,0.00,0.00,0.00,0,1.00,NaN,0.00,NaN,0.00,NaN,0.00,NaN,0.00,0,0,0.00,0.00,1.00,0.00,0.00,0.00
323,G,1,0.00,Sowing Salt,Sorcery,unknown,26,0,0,0.00,0.00,0.00,0,1.00,NaN,0.00,NaN,0.00,NaN,0.00,NaN,0.00,0,0,0.00,0.00,1.00,0.00,0.00,0.00

In [29]:
types[types.final_qty>0]

,sb,final_qty,type,n_dls,sum,mean_rnd,mean,std,min,max,% copies = mean-2,% copies = mean-1,% copies = mean,% copies = mean+1,% copies = mean+2
1,0,4.00,Artifact,115,435,4.00,3.78,14.58,0,16,0.12,0.01,0.21,0.10,0.05
3,0,12.00,Creature,115,1536,13.00,13.36,100.18,0,27,0.01,0.15,0.05,0.12,0.15
6,0,4.00,Instant,115,623,5.00,5.42,20.04,0,14,0.03,0.21,0.00,0.06,0.01
7,0,22.00,Land,115,2694,23.00,23.43,146.80,11,29,0.01,0.34,0.10,0.15,0.03
10,0,10.00,Sorcery,115,1288,11.00,11.20,65.62,4,20,0.09,0.18,0.08,0.08,0.03
12,1,2.00,Artifact,115,310,3.00,2.70,9.27,0,8,0.10,0.37,0.13,0.12,0.11
18,1,2.00,Instant,115,432,4.00,3.76,17.07,0,8,0.19,0.12,0.16,0.10,0.14
22,1,3.00,Sorcery,115,349,3.00,3.03,17.36,0,7,0.10,0.14,0.17,0.09,0.15

In [30]:
# conditions = (df.sb==1) & (((df.type=="Removal") & (df.subtype=="Art/Ench")) | (df.name=="Annul"))
# display(df[conditions])
# df[conditions]["mean"].sum()